plot_names: ['EpRewMean', ['rew_dist_px_mnist_force', 'rew_px_mnist_force', 'rew_mnist_force', 'rew_mnist', 'rew_total'], 'prob']
reward_interval:
    # reward_interval: [start, end] when the reward is applied. If not specified then the reward is applied right away.
    # If null is specified as start (or the whole parameter) then the reward is not applied at all
    dist:  [0, 25000]
    px:    [0, 50000]
    mnist: [0, None]